### ISSUE TITLE
Triggering tests through Jenkins on a self-hosted Selenium Server leads to Exceptions

### ISSUE THREAD

**Issue by rmadakasira** [forcedotcom/cinnamon#41]
Hi,

I am able to run tests successfully through UI by clicking on "Execute Tests" in "Test Console" page. I am now trying to trigger tests through my Jenkins job, and it triggers the below error. I am able to trigger tests when the "WebDriver Service Provide" is sauceLabs.

Based on this I would imagine, I will have to make few more configuration changes, and I don't want to re-invent the wheel. Your help is appreciated. Thanks.

Mar 03, 2015 11:15:36 AM cinnamon.Ccli main
SEVERE: An unexpected error occurred. aborting test
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to java.util.Map
at cinnamon.CinnamontTestSuite.getMapFromJson(CinnamontTestSuite.java:82)
at cinnamon.CinnamontTestSuite.run(CinnamontTestSuite.java:158)
at cinnamon.Ccli.run(Ccli.java:80)
at cinnamon.Ccli.main(Ccli.java:48)

**Comment by nadeemg** [comment]
Hi @rmadakasira, 

I'm assuming that you've written your own class implementing RemoteWebDriverServiceProvider and configured the Settings page to point to your self-hosted server. 
- Have you been able to trigger a test manually, i.e. through the TestConsole, against your self-hosted selenium server?
- What version of ccli are you using?

**Comment by rmadakasira** [comment]
@nadeemg 
- Yes, I am to run the tests manually from Test Console against my self-hosted selenium server.
  - I think I am using the initial version of ccli that I got from here (https://github.com/ryojiosawa/cinnamon-boilerplate)

**Comment by nadeemg** [comment]
@rmadakasira best guess is that the version of ccli you're using is outdated, and isn't working well with cinnamon. Unfortunately, we do not have a plan for releasing ccli.

Could you rewrite your jenkins job to go through the UI instead?

**Comment by rmadakasira** [comment]
I don't think I follow you. Can you please explain what you mean ? Thanks.

**Comment by nadeemg** [comment]
Since you can manually run tests, why not write a little java or python using webdriver to login to your DE org and run the tests through the UI? This isn't a great solution, I know, but like I said, we have no plans for releasing ccli at this point.

**Comment by drorm** [comment]
Does this mean that the REST API is not supported either? Couldn't find documentation for it anywhere.

You should probably update http://forcedotcom.github.io/cinnamon/ and remove the mention of ccli.
